# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -P travis -B

# Отправлять уведомление на почту gh0st84@mail.ru
notifications:
  email:
    recipients:
      - gh0st84@mail.ru
    on_success: never # default: change
    on_failure: always # default: always